package org.nekomanga.presentation.theme.colorschemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Kitty's own palette: a ginger tabby primary with teal secondary and tertiary accents. Generated
 * with Material Color Utilities (expressive variant, seed #2FA38F).
 */
internal object KittyColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF8A5010),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFDCC1),
            onPrimaryContainer = Color(0xFF6C3A00),
            inversePrimary = Color(0xFFFFB877),
            secondary = Color(0xFF3D6373),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFC1E9FB),
            onSecondaryContainer = Color(0xFF244C5B),
            tertiary = Color(0xFF19686C),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFA8EFF2),
            onTertiaryContainer = Color(0xFF004F52),
            background = Color(0xFFF1FBFA),
            onBackground = Color(0xFF141D1D),
            surface = Color(0xFFF1FBFA),
            onSurface = Color(0xFF141D1D),
            surfaceVariant = Color(0xFFD3E6E5),
            onSurfaceVariant = Color(0xFF394A49),
            surfaceTint = Color(0xFF8A5010),
            inverseSurface = Color(0xFF293232),
            inverseOnSurface = Color(0xFFE8F3F2),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            outline = Color(0xFF697A7A),
            outlineVariant = Color(0xFFB8CAC9),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFFF1FBFA),
            surfaceContainer = Color(0xFFE6F0EF),
            surfaceContainerHigh = Color(0xFFE0EAE9),
            surfaceContainerHighest = Color(0xFFDAE5E4),
            surfaceContainerLow = Color(0xFFEBF6F5),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFD2DCDB),
            primaryFixed = Color(0xFFFFDCC1),
            primaryFixedDim = Color(0xFFFFB877),
            onPrimaryFixed = Color(0xFF2E1500),
            onPrimaryFixedVariant = Color(0xFF6C3A00),
            secondaryFixed = Color(0xFFC1E9FB),
            secondaryFixedDim = Color(0xFFA5CCDE),
            onSecondaryFixed = Color(0xFF001F29),
            onSecondaryFixedVariant = Color(0xFF244C5B),
            tertiaryFixed = Color(0xFFA8EFF2),
            tertiaryFixedDim = Color(0xFF8CD2D6),
            onTertiaryFixed = Color(0xFF002021),
            onTertiaryFixedVariant = Color(0xFF004F52),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFFFB877),
            onPrimary = Color(0xFF4C2700),
            primaryContainer = Color(0xFF6C3A00),
            onPrimaryContainer = Color(0xFFFFDCC1),
            inversePrimary = Color(0xFF8A5010),
            secondary = Color(0xFFA5CCDE),
            onSecondary = Color(0xFF073543),
            secondaryContainer = Color(0xFF244C5B),
            onSecondaryContainer = Color(0xFFC1E9FB),
            tertiary = Color(0xFF8CD2D6),
            onTertiary = Color(0xFF003739),
            tertiaryContainer = Color(0xFF004F52),
            onTertiaryContainer = Color(0xFFA8EFF2),
            background = Color(0xFF0C1515),
            onBackground = Color(0xFFDAE5E4),
            surface = Color(0xFF0C1515),
            onSurface = Color(0xFFDAE5E4),
            surfaceVariant = Color(0xFF394A49),
            onSurfaceVariant = Color(0xFFB8CAC9),
            surfaceTint = Color(0xFFFFB877),
            inverseSurface = Color(0xFFDAE5E4),
            inverseOnSurface = Color(0xFF293232),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            outline = Color(0xFF829493),
            outlineVariant = Color(0xFF394A49),
            scrim = Color(0xFF000000),
            surfaceBright = Color(0xFF313B3B),
            surfaceContainer = Color(0xFF182121),
            surfaceContainerHigh = Color(0xFF222C2B),
            surfaceContainerHighest = Color(0xFF2D3736),
            surfaceContainerLow = Color(0xFF141D1D),
            surfaceContainerLowest = Color(0xFF071010),
            surfaceDim = Color(0xFF0C1515),
            primaryFixed = Color(0xFFFFDCC1),
            primaryFixedDim = Color(0xFFFFB877),
            onPrimaryFixed = Color(0xFF2E1500),
            onPrimaryFixedVariant = Color(0xFF6C3A00),
            secondaryFixed = Color(0xFFC1E9FB),
            secondaryFixedDim = Color(0xFFA5CCDE),
            onSecondaryFixed = Color(0xFF001F29),
            onSecondaryFixedVariant = Color(0xFF244C5B),
            tertiaryFixed = Color(0xFFA8EFF2),
            tertiaryFixedDim = Color(0xFF8CD2D6),
            onTertiaryFixed = Color(0xFF002021),
            onTertiaryFixedVariant = Color(0xFF004F52),
        )
}
